"""Multiview inference using pre-computed views.

This script runs inference using views that were pre-generated by batch_view_generation.py.

Usage:
    python -m src.inference.mvgen_inference_precomputed \
        --model_path ./checkpoints/Qwen2.5-VL-7B-SFT-HF-Multiview \
        --test_data ./data/benchmark/3dsrbench_v1_vlmevalkit_circular.tsv \
        --views_dir ./data/benchmark/generated_views \
        --output_path ./results/multiview_eval.xlsx \
        --gpu_ids "0,1,2,3"
"""

import os
import json
import base64
import hashlib
import logging
import argparse
import string
from pathlib import Path
from typing import Dict, List, Optional
from io import BytesIO

import torch
import pandas as pd
from PIL import Image
from tqdm.auto import tqdm
from transformers import Qwen2_5_VLForConditionalGeneration, AutoProcessor
from torch.multiprocessing import Process, set_start_method, Manager

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

SYSTEM_PROMPT = (
    "A conversation between User and Assistant. The user asks a question, and the Assistant solves it. The assistant "
    "first thinks about the reasoning process in the mind and then provides the user with the answer. The reasoning "
    "process and answer are enclosed within <think> </think> and <answer> </answer> tags, respectively, i.e., "
    "<think> reasoning process here </think><answer> answer here </answer>"
)


def get_image_hash(image_data: str) -> str:
    """Generate hash for image data to use as unique identifier."""
    return hashlib.md5(image_data.encode()[:1000]).hexdigest()[:12]


def decode_image(image_string: str) -> Image.Image:
    """Decode base64 image string to PIL Image."""
    image_data = base64.b64decode(image_string)
    return Image.open(BytesIO(image_data)).convert('RGB')


def load_view_mapping(views_dir: str) -> Dict:
    """Load the view mapping file."""
    mapping_path = os.path.join(views_dir, "view_mapping.json")
    if os.path.exists(mapping_path):
        with open(mapping_path, "r") as f:
            return json.load(f)
    return {}


def init_model(model_path: str, gpu_id: int):
    """Initialize model on specific GPU."""
    model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
        model_path,
        torch_dtype=torch.bfloat16,
        attn_implementation="sdpa",
        device_map=f"cuda:{gpu_id}",
    )
    processor = AutoProcessor.from_pretrained(
        model_path,
        padding_side="left",
        use_fast=True,
    )
    return model, processor


def build_multiview_message(
    images: List[Image.Image],
    angles: List[float],
    question: str,
    options: Dict[str, str],
) -> List[Dict]:
    """Build conversation message with multiple views.

    CRITICAL: Format must match training format from sft_multiview.py:
    - Uses "View 1 (rotation: X degrees):" format
    - Exactly 2 images (not 3)
    """
    # Format options
    opts_text = "\n".join(f"{k}. {v}" for k, v in options.items() if v and not pd.isna(v))
    question_text = (
        f"Question: {question}\n"
        f"Options:\n{opts_text}\n"
        f"Please select the correct answer from the options above."
    )

    # Build content with multiple images
    if len(images) == 2:
        # CRITICAL: Match training format exactly (sft_multiview.py lines 440-445)
        prompt_text = (
            f"View 1 (rotation: {angles[0]:.0f} degrees):\n"
            f"View 2 (rotation: {angles[1]:.0f} degrees):\n\n"
            f"{question_text}"
        )
        content = [
            {"type": "image"},  # First image (primary view)
            {"type": "image"},  # Second image (secondary view)
            {"type": "text", "text": prompt_text},
        ]
    else:
        # Single view fallback
        content = [
            {"type": "image"},
            {"type": "text", "text": question_text},
        ]

    return [
        {"role": "system", "content": [{"type": "text", "text": SYSTEM_PROMPT}]},
        {"role": "user", "content": content}
    ]


def infer_batch_multiview(
    batch_data: List[Dict],
    model,
    processor,
    view_mapping: Dict,
    views_dir: str,
    angles: List[float],
) -> List[str]:
    """Run inference on a batch with multiview support.

    CRITICAL: Training used exactly 2 views (+10°, -10°), NOT including original.
    We must match this format for proper inference.
    """
    batch_messages = []
    batch_images = []

    for item in batch_data:
        img_hash = get_image_hash(item["image"])

        # CRITICAL: Match training - use only 2 views, NO original
        # Training used angles [10.0, -10.0] without the original image
        images = []
        used_angles = []

        # Filter to get non-zero angles (the actual rotated views)
        target_angles = [a for a in angles if a != 0]

        if img_hash in view_mapping:
            for angle in target_angles:
                angle_key = str(float(angle))
                if angle_key in view_mapping[img_hash]:
                    view_path = view_mapping[img_hash][angle_key]
                    if os.path.exists(view_path):
                        images.append(Image.open(view_path).convert("RGB"))
                        used_angles.append(angle)

        # Fallback: if views not available, use original twice (degraded mode)
        if len(images) != 2:
            logger.warning(f"Expected 2 views for {img_hash}, got {len(images)}. Using original image as fallback.")
            original_image = decode_image(item["image"])
            images = [original_image, original_image]
            used_angles = [0.0, 0.0]

        # Build message
        options = {k: item.get(k) for k in ["A", "B", "C", "D"]}
        message = build_multiview_message(images, used_angles, item["question"], options)
        batch_messages.append(message)
        batch_images.append(images)

    # Process batch
    texts = [processor.apply_chat_template(msg, tokenize=False, add_generation_prompt=True)
             for msg in batch_messages]

    # Flatten images for processor
    all_images = []
    for img_list in batch_images:
        all_images.extend(img_list)

    inputs = processor(
        text=texts,
        images=all_images,
        padding=True,
        return_tensors="pt",
    )
    inputs = inputs.to(model.device)

    # Generate
    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=512,
            do_sample=False,
            top_p=0.001,
            top_k=1,
            temperature=0.01,
        )

    # Decode
    output_texts = processor.batch_decode(
        output_ids[:, inputs.input_ids.shape[1]:],
        skip_special_tokens=True,
    )

    return output_texts


def infer_on_single_gpu(
    model_path: str,
    gpu_id: int,
    data_chunk: List[Dict],
    view_mapping: Dict,
    views_dir: str,
    angles: List[float],
    batch_size: int,
    results: Dict,
):
    """Run inference on a single GPU."""
    model, processor = init_model(model_path, gpu_id)

    predictions = []
    batches = [data_chunk[i:i+batch_size] for i in range(0, len(data_chunk), batch_size)]

    for batch in tqdm(batches, desc=f"GPU {gpu_id}", position=gpu_id, leave=False):
        try:
            batch_preds = infer_batch_multiview(
                batch, model, processor, view_mapping, views_dir, angles
            )
            predictions.extend(batch_preds)
        except Exception as e:
            logger.error(f"Error on GPU {gpu_id}: {e}")
            predictions.extend([""] * len(batch))

    results[gpu_id] = predictions


def main():
    parser = argparse.ArgumentParser(description="Multiview inference with pre-computed views")
    parser.add_argument("--model_path", type=str, required=True)
    parser.add_argument("--test_data", type=str, required=True)
    parser.add_argument("--views_dir", type=str, required=True)
    parser.add_argument("--output_path", type=str, required=True)
    parser.add_argument("--angles", type=str, default="10,-10",
                        help="Rotation angles for multi-view (e.g., '10,-10' for ±10 degree views)")
    parser.add_argument("--batch_size", type=int, default=1)  # Small batch due to multi-image
    parser.add_argument("--gpu_ids", type=str, default="0")

    args = parser.parse_args()

    # Parse angles
    angles = [float(a.strip()) for a in args.angles.split(",")]
    logger.info(f"Using angles: {angles}")

    # Load view mapping
    view_mapping = load_view_mapping(args.views_dir)
    logger.info(f"Loaded view mapping with {len(view_mapping)} images")

    # Load test data
    logger.info(f"Loading test data from {args.test_data}")
    test_data = pd.read_csv(args.test_data, sep="\t")
    data_list = test_data.to_dict("records")
    logger.info(f"Loaded {len(data_list)} samples")

    # Parse GPU IDs
    gpu_ids = [int(g.strip()) for g in args.gpu_ids.split(",")]
    logger.info(f"Using GPUs: {gpu_ids}")

    # Multi-GPU inference
    if len(gpu_ids) > 1:
        set_start_method("spawn", force=True)
        manager = Manager()
        results = manager.dict()

        chunk_size = len(data_list) // len(gpu_ids)
        processes = []

        for i, gpu_id in enumerate(gpu_ids):
            start_idx = i * chunk_size
            end_idx = start_idx + chunk_size if i < len(gpu_ids) - 1 else len(data_list)
            chunk = data_list[start_idx:end_idx]

            p = Process(
                target=infer_on_single_gpu,
                args=(args.model_path, gpu_id, chunk, view_mapping,
                      args.views_dir, angles, args.batch_size, results)
            )
            p.start()
            processes.append(p)

        for p in processes:
            p.join()

        # Collect results
        all_predictions = []
        for gpu_id in gpu_ids:
            all_predictions.extend(results[gpu_id])
    else:
        # Single GPU
        model, processor = init_model(args.model_path, gpu_ids[0])
        all_predictions = []

        batches = [data_list[i:i+args.batch_size] for i in range(0, len(data_list), args.batch_size)]
        for batch in tqdm(batches, desc="Inference"):
            preds = infer_batch_multiview(
                batch, model, processor, view_mapping, args.views_dir, angles
            )
            all_predictions.extend(preds)

    # Save results
    test_data["prediction"] = all_predictions

    output_path = Path(args.output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if str(output_path).endswith(".xlsx"):
        test_data.to_excel(output_path, index=False)
    else:
        test_data.to_csv(output_path, sep="\t", index=False)

    logger.info(f"Results saved to {output_path}")

    # Calculate accuracy
    import re
    def extract_answer(pred):
        """Extract answer from model prediction with fallback patterns."""
        pred_str = str(pred).strip()

        # Primary pattern: <answer>X</answer> (trained format)
        match = re.search(r'<answer>\s*([A-D])\s*</answer>', pred_str, re.IGNORECASE)
        if match:
            return match.group(1).upper()

        # Fallback 1: "answer is X" pattern
        match = re.search(r'(?:the )?(?:final )?answer is\s*([A-D])', pred_str, re.IGNORECASE)
        if match:
            return match.group(1).upper()

        # Fallback 2: Look for isolated capital letter at end
        match = re.search(r'\b([A-D])\b(?!.*\b[A-D]\b)', pred_str)
        if match:
            return match.group(1).upper()

        logger.warning(f"Could not extract answer from: {pred_str[:100]}...")
        return ""

    test_data["pred_answer"] = test_data["prediction"].apply(extract_answer)
    test_data["correct"] = test_data["pred_answer"] == test_data["answer"].str.upper()
    accuracy = test_data["correct"].mean() * 100

    logger.info(f"Overall accuracy: {accuracy:.2f}%")


if __name__ == "__main__":
    main()
